blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/byarcadia-app/plutus/discussions
    about: If the library works as expected but you need help or want to discuss ideas, start a discussion.
