name: Secrets scan

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: byarcadia-app/gh-actions-public/.github/workflows/secrets-scan-on-pr.yaml@main
