name: Secrets scan on push

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: byarcadia-app/gh-actions-public/.github/workflows/secrets-scan-on-push.yaml@main
